### ISSUE TITLE
error generating code

### ISSUE THREAD

**Issue by kirchaj** [TiagoSilvaPereira/vemto-issues#100]
```
TypeError: window.changeCase[e] is not a function
    at String.case (app://./js/chunk-common.cc073f4f.js:1:31430)
    at Object.eval (eval at compile (app://./js/chunk-vendors.d8d07ddf.js:134:77882), <anonymous>:24:48)
    at i.compile (app://./js/chunk-vendors.d8d07ddf.js:134:77915)
    at v.compile (app://./js/generator.ee72331e.js:1:5152)
    at v.compileFromFile (app://./js/generator.ee72331e.js:1:5062)
    at te.renderToString (app://./js/generator.ee72331e.js:1:6116)
    at te.render (app://./js/generator.ee72331e.js:1:5584)
    at oe.generateCrudTranslations (app://./js/generator.ee72331e.js:1:24698)
    at oe.generate (app://./js/generator.ee72331e.js:1:23393)
    at async oe.start (app://./js/generator.ee72331e.js:1:23255)
```

---

vemto 0.7.8
Electron 8.5.5
win32 10.0.19041
Locale: en-US

**Comment by kirchaj** [comment]
This was caused by a blank label in the application area

**Comment by TiagoSilvaPereira** [comment]
Hi @kirchaj thank you for reporting, I'll treat this error to avoid it happening again
