### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ocontreras4** [TiagoSilvaPereira/vemto-issues#12]
![verror01](https://user-images.githubusercontent.com/42900101/94565489-e6de1f80-022e-11eb-8d40-0275fcc2cc20.png)
```
NavigationDuplicated: Avoided redundant navigation to current location: "/projects/1/schema".
    at $e (app://./js/chunk-vendors.f2f83789.js:194:17090)
    at Be (app://./js/chunk-vendors.f2f83789.js:194:16669)
    at t.et.confirmTransition (app://./js/chunk-vendors.f2f83789.js:194:20877)
    at t.et.transitionTo (app://./js/chunk-vendors.f2f83789.js:194:20164)
    at t.push (app://./js/chunk-vendors.f2f83789.js:194:23892)
    at app://./js/chunk-vendors.f2f83789.js:194:27581
    at new Promise (<anonymous>)
    at Dt.push (app://./js/chunk-vendors.f2f83789.js:194:27544)
    at a.goTo (app://./js/project_main.483cb940.js:1:7478)
    at click (app://./js/project_main.483cb940.js:1:1276)
```

---

vemto 0.4.14
Electron 8.5.0
win32 10.0.18363
Locale: en-US

**Comment by TiagoSilvaPereira** [comment]
Hi @ocontreras4 thanks for reporting. This bug was fixed on 0.4.15... please upgrade to the latest version to avoid this message.
