### ISSUE TITLE
Hello. First of all I would like to praise the project, I am a PHP developer and I admit that this system seems to be very efficient.

### ISSUE THREAD

**Issue by IgorPC** [TiagoSilvaPereira/vemto-issues#20]
```
Error: Command failed: git clone https://github.com/laravel/laravel.git C:\Users\Igor\ Coutinho\Desktop\vemto\vemto_test -b 7.x
fatal: Too many arguments.

usage: git clone [<options>] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --progress            force progress reporting
    -n, --no-checkout     don't create a checkout
    --bare                create a bare repository
    --mirror              create a mirror repository (implies bare)
    -l, --local           to clone from a local repository
    --no-hardlinks        don't use local hardlinks, always copy
    -s, --shared          setup as shared repository
    --recurse-submodules[=<pathspec>]
                          initialize submodules in the clone
    --recursive ...       alias of --recurse-submodules
    -j, --jobs <n>        number of submodules cloned in parallel
    --template <template-directory>
                          directory from which templates will be used
    --reference <repo>    reference repository
    --reference-if-able <repo>
                          reference repository
    --dissociate          use --reference only while cloning
    -o, --origin <name>   use <name> instead of 'origin' to track upstream
    -b, --branch <branch>
                          checkout <branch> instead of the remote's HEAD
    -u, --upload-pack <path>
                          path to git-upload-pack on the remote
    --depth <depth>       create a shallow clone of that depth
    --shallow-since <time>
                          create a shallow clone since a specific time
    --shallow-exclude <revision>
                          deepen history of shallow clone, excluding rev
    --single-branch       clone only one branch, HEAD or --branch
    --no-tags             don't clone any tags, and make later fetches not to follow them
    --shallow-submodules  any cloned submodules will be shallow
    --separate-git-dir <gitdir>
                          separate git dir from working tree
    -c, --config <key=value>
                          set config inside the new repository
    --server-option <server-specific>
                          option to transmit
    -4, --ipv4            use IPv4 addresses only
    -6, --ipv6            use IPv6 addresses only
    --filter <args>       object filtering
    --remote-submodules   any cloned submodules will use their remote-tracking branch
    --sparse              initialize sparse-checkout file to include only files at root


    at checkExecSyncError (child_process.js:634:11)
    at execSync (child_process.js:670:15)
    at electron/js2c/asar.js:727:23
    at o.executeCommand (app://./js/chunk-common.54d7ab25.js:1:24749)
    at app://./js/generator.a02083a4.js:1:21810
    at new Promise (<anonymous>)
    at fe.clone (app://./js/generator.a02083a4.js:1:21576)
    at fe.start (app://./js/generator.a02083a4.js:1:21553)
    at mt.callGenerators (app://./js/generator.a02083a4.js:1:33792)
    at mt.start (app://./js/generator.a02083a4.js:1:33485)
```

However, when I was generating a test code, I received the following error, can you help me with this?

---

vemto 0.5.3
Electron 8.5.2
win32 10.0.19041
Locale: pt-BR

**Comment by IgorPC** [comment]
An issue has already been opened as the same objective
