### ISSUE TITLE
Error adding relationships

### ISSUE THREAD

**Issue by dblanco-dev** [TiagoSilvaPereira/vemto-issues#205]
```
Error: Related model has no primary key when trying to create foreign
    at Proxy.value (app://./js/chunk-common.038e8b90.js:1:101289)
    at Proxy.value (app://./js/chunk-common.038e8b90.js:1:101005)
    at Proxy.value (app://./js/chunk-common.038e8b90.js:1:88273)
    at Proxy.value (app://./js/chunk-common.038e8b90.js:1:87831)
    at Proxy.value (app://./js/chunk-common.038e8b90.js:1:87637)
    at app://./js/project_schema.94f25dcc.js:1:54859
```

---

vemto 0.9.9
Electron 8.5.5
win32 10.0.19043
Locale: es-419

![Snipaste_2021-08-02_19-58-29](https://user-images.githubusercontent.com/33554631/127946034-1d676ff9-92b5-43b2-b3dc-ee5f41a31134.png)
![Snipaste_2021-08-02_19-58-45](https://user-images.githubusercontent.com/33554631/127946035-80dd7fc2-2dc3-4215-b9e8-189966fbda25.png)

**Comment by TiagoSilvaPereira** [comment]
Hi @dblanco-dev please change the **id** field in the User model to be a **primary key** before trying to create the related foreign key
![image](https://user-images.githubusercontent.com/11933789/128020823-b6931e5a-d428-41db-a5a6-5514fd5d0789.png)
