### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by shofeather** [TiagoSilvaPereira/vemto-issues#230]
```
TypeError: Cannot read property 'entity' of null
    at app://./js/project_schema.6b8ca738.js:1:73448
    at Array.forEach (<anonymous>)
    at app://./js/project_schema.6b8ca738.js:1:73400
    at Array.forEach (<anonymous>)
    at o.getConnections (app://./js/project_schema.6b8ca738.js:1:73193)
    at o.<anonymous> (app://./js/project_schema.6b8ca738.js:1:72547)
    at Array.<anonymous> (app://./js/chunk-vendors.b18246bf.js:83:12806)
    at pt (app://./js/chunk-vendors.b18246bf.js:83:12201)
```

---

vemto 0.9.10
Electron 8.5.5
win32 10.0.19043
Locale: en-US

**Comment by TiagoSilvaPereira** [comment]
Hi @shofeather thank you for reporting... I'll check it asap

**Comment by TiagoSilvaPereira** [comment]
Hi @shofeather I tried to reproduce it here, but without success... seems like an isolated bug... please reopen if it happens again
