### ISSUE TITLE
[BUG] Maximum call stack size exceeded

### ISSUE THREAD

**Issue by BriscoPeas93** [TiagoSilvaPereira/vemto-issues#24]
```
RangeError: Maximum call stack size exceeded
    at o.getFilePathByKey (app://./js/chunk-vendors.c7dc88e9.js:37:32047)
    at o.get (app://./js/chunk-vendors.c7dc88e9.js:37:31142)
    at s.get (app://./js/chunk-vendors.c7dc88e9.js:115:2735)
    at e.exports.getTableData (app://./js/chunk-vendors.c7dc88e9.js:389:4986)
    at e.exports.getItemIndex (app://./js/chunk-vendors.c7dc88e9.js:389:6782)
    at e.exports.execute (app://./js/chunk-vendors.c7dc88e9.js:89:1521)
    at f.executeRelationship (app://./js/chunk-vendors.c7dc88e9.js:57:4571)
    at Object.__get [as get] (app://./js/chunk-vendors.c7dc88e9.js:57:2312)
    at Proxy.belongsToAnotherEntity (app://./js/chunk-common.91b0686d.js:1:51716)
    at app://./js/chunk-common.91b0686d.js:1:42658
```

---

vemto 0.5.4
Electron 8.5.2
darwin 19.6.0
Locale: fr

**Comment by TiagoSilvaPereira** [comment]
Hi @BriscoPeas93 could you please send a screenshot of the Schema so I can reproduce the error? Thank you

**Comment by TiagoSilvaPereira** [comment]
Hi @BriscoPeas93 this problem was happening when the Schema had a circular relation, for example (A User has many Pets and a Pet has many users, but not using a pivot table with "Belongs to Many" relationship). So, in the new Vemto 0.5.5 that I launched today, it is no longer more possible to add a circular relation, as the correct way to do it is using a **"Belongs to Many"** relationship.

If you have some relationships like that, please remove them and add a "belongs to many" relationship.

I hope it helps. If you have another problem, please feel free to open an issue here.

Have a nice day! Cheers
