### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by marekszotpl** [TiagoSilvaPereira/vemto-issues#241]
```
Error: Request failed with status code 500
    at e.exports (app://./js/chunk-vendors.74aa9267.js:85:12146)
    at e.exports (app://./js/chunk-vendors.74aa9267.js:260:2244)
    at XMLHttpRequest.d.onreadystatechange (app://./js/chunk-vendors.74aa9267.js:623:2209)
```

---

vemto 0.9.11
Electron 8.5.5
win32 10.0.19042
Locale: pl

**Comment by TiagoSilvaPereira** [comment]
@marekszotpl sorry, I just fixed it... no need to update Vemto, it was a problem on owr server
