### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by digidoers** [TiagoSilvaPereira/vemto-issues#243]
```
Error: Request failed with status code 500
    at e.exports (app://./js/chunk-vendors.74aa9267.js:85:12146)
    at e.exports (app://./js/chunk-vendors.74aa9267.js:260:2244)
    at XMLHttpRequest.d.onreadystatechange (app://./js/chunk-vendors.74aa9267.js:623:2209)
```

---

vemto 0.9.11
Electron 8.5.5
win32 10.0.19042
Locale: en-US

**Comment by TiagoSilvaPereira** [comment]
@digidoers sorry, I just fixed it... no need to update Vemto, it was a problem on our server
