### ISSUE TITLE
Problem?

### ISSUE THREAD

**Issue by martin-masterclass** [TiagoSilvaPereira/vemto-issues#297]
```
Error: Invalid URL
    at electron/js2c/browser_init.js:6846:67
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:6711:27)
    at IpcMainImpl.emit (events.js:210:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3930:23)
    at WebContents.emit (events.js:210:5)
```

---

vemto 1.1.2
Electron 8.5.5
darwin 21.4.0
Locale: de

**Comment by TiagoSilvaPereira** [comment]
Hi @martin-masterclass could you please send some screenshots or a small video showing this happening? I could not reproduce it here

**Comment by martin-masterclass** [comment]
Ok Tiago, sorry next time I do that. You can delete this issue for now. It
did not happen again. Still testing Vemto. Regards.
