### ISSUE TITLE
Cannot find module 'vue-debounce'

### ISSUE THREAD

**Issue by smayzes** [TiagoSilvaPereira/vemto-issues#3]
When I first opened the app I get this error. I cannot see anything else but a blank screen. 

```
Error: Cannot find module 'vue-debounce'
Require stack:
- electron/js2c/renderer_init
    at Module._resolveFilename (internal/modules/cjs/loader.js:798:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/renderer_init.js:752:16)
    at Module._load (internal/modules/cjs/loader.js:691:27)
    at Function.Module._load (electron/js2c/asar.js:748:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.9874 (app://./js/index.227591be.js:1:27289)
    at c (app://./js/index.227591be.js:1:1354)
    at Module.56d7 (app://./js/index.227591be.js:1:26567)
    at c (app://./js/index.227591be.js:1:1354)
```

---

vemto 0.4.13
Electron 8.5.0
darwin 19.6.0
Locale: en-US
macOS: Catalina

**Comment by TiagoSilvaPereira** [comment]
Hi, @smayzes thanks for reporting. I just fixed it on 0.4.14. Cheers
