### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by goldensio** [TiagoSilvaPereira/vemto-issues#308]
```
TypeError: Cannot read property 'type' of undefined
    at Function.getCorrectInputFromFieldAndCrud (app://./js/chunk-common.35514d1f.js:1:66271)
    at Proxy.addInputToCrud (app://./js/chunk-common.35514d1f.js:1:26434)
    at app://./js/chunk-common.35514d1f.js:1:35217
    at Array.forEach (<anonymous>)
    at Proxy.addInputsFromModel (app://./js/chunk-common.35514d1f.js:1:35204)
    at Function.fromModel (app://./js/chunk-common.35514d1f.js:1:34541)
    at o.create (app://./js/project_apps.c4309195.js:1:12235)
    at app://./js/project_apps.c4309195.js:1:12207
```

---

vemto 1.1.3
Electron 8.5.5
win32 10.0.19044
Locale: it

**Comment by TiagoSilvaPereira** [comment]
Hi @goldensio please check #283 for a workaround

I'll close for now as it seems to be a duplicate. We'll fix the Filament plugin soon.
