### ISSUE TITLE
Error thrown when adding BelongsToMany relationship

### ISSUE THREAD

**Issue by raftalks** [TiagoSilvaPereira/vemto-issues#316]
I just caught this error when I was adding belongsToMany relationship to a new entity I was working on.

```
Error: Related model has no primary key when trying to create foreign
    at Proxy.getOrCreateForeignField (app://./js/chunk-common.8eaedb88.js:1:119365)
    at Proxy.addForeign (app://./js/chunk-common.8eaedb88.js:1:119075)
    at Proxy.createPivotFields (app://./js/chunk-common.8eaedb88.js:1:56818)
    at Proxy.createPivot (app://./js/chunk-common.8eaedb88.js:1:56667)
    at Proxy.process (app://./js/chunk-common.8eaedb88.js:1:53507)
    at Proxy.processAndSave (app://./js/chunk-common.8eaedb88.js:1:53456)
    at app://./js/project_schema.5596bd53.js:1:76893
```

---

vemto 1.1.4
Electron 8.5.5
darwin 21.4.0
Locale: en-GB

**Comment by raftalks** [comment]
I figured out as the error msg clearly indicated the table didn't have the primary ID set. Once I have set, it is working fine.
