### ISSUE TITLE
Error standalone field

### ISSUE THREAD

**Issue by dblanco-dev** [TiagoSilvaPereira/vemto-issues#343]
```
TypeError: Cannot read property 'nullable' of null
    at Proxy.fixNullableValidationFromField (app://./js/chunk-common.fe76fb8b.js:1:72663)
    at Proxy.fixValidationFromType (app://./js/chunk-common.fe76fb8b.js:1:72562)
    at o.create (app://./js/project_crud.a0c809af.js:1:55315)
    at app://./js/project_crud.a0c809af.js:1:54970
```

---

vemto 1.1.8
Electron 8.5.5
win32 10.0.22000
Locale: es-419

![image](https://user-images.githubusercontent.com/33554631/177619337-98fec6b0-6ac2-4cf6-8766-66ae87e14b3f.png)

**Comment by TiagoSilvaPereira** [comment]
Fixed on 1.1.9
