### ISSUE TITLE
vemto error when select bootstrap

### ISSUE THREAD

**Issue by hadi78m** [TiagoSilvaPereira/vemto-issues#345]
```
Error: timeout exceeded
    at e.exports (app://./js/chunk-vendors.6b4aecd2.js:80:13835)
    at XMLHttpRequest.y.ontimeout (app://./js/chunk-vendors.6b4aecd2.js:645:2784)
```

---

vemto 1.1.8
Electron 8.5.5
win32 10.0.19042
Locale: en-US

**Comment by TiagoSilvaPereira** [comment]
It seems this was just a one-off problem. Please feel free to open the issue again if it is still hapenning
