### ISSUE TITLE
probllem

### ISSUE THREAD

**Issue by wings-dev** [TiagoSilvaPereira/vemto-issues#370]
```
Error: Related model has no primary key when trying to create foreign
    at Proxy.getOrCreateForeignField (app://./js/chunk-common.9f1d38d9.js:1:123781)
    at Proxy.addForeign (app://./js/chunk-common.9f1d38d9.js:1:123491)
    at Proxy.createPivotFields (app://./js/chunk-common.9f1d38d9.js:1:58500)
    at Proxy.createPivot (app://./js/chunk-common.9f1d38d9.js:1:58349)
    at Proxy.process (app://./js/chunk-common.9f1d38d9.js:1:55189)
    at Proxy.processAndSave (app://./js/chunk-common.9f1d38d9.js:1:55138)
    at app://./js/project_schema.4895f368.js:1:85335
```

---

vemto 1.1.9
Electron 8.5.5
darwin 21.1.0
Locale: tr

**Comment by TiagoSilvaPereira** [comment]
Hi @wings-dev this error happens if you try to create a relation using a model that doesn't have a primary key. Please add a primary key to the related model before creating the relation
