### ISSUE TITLE
Error: timeout exceeded

### ISSUE THREAD

**Issue by TheBiGBoSS6000** [TiagoSilvaPereira/vemto-issues#373]
```
Error: timeout exceeded
    at e.exports (app://./js/chunk-vendors.6b4aecd2.js:80:13835)
    at XMLHttpRequest.y.ontimeout (app://./js/chunk-vendors.6b4aecd2.js:645:2784)
```

---

vemto 1.1.9
Electron 8.5.5
win32 10.0.19044
Locale: en-US

**Comment by TiagoSilvaPereira** [comment]
Hi @TheBiGBoSS6000 could you please give more details on when and where this problem occurs?

**Comment by TiagoSilvaPereira** [comment]
Closing due to lack of details
