### ISSUE TITLE
Issues with npm build on vemto

### ISSUE THREAD

**Issue by kodekrib** [TiagoSilvaPereira/vemto-issues#385]
Hello, whenever I try to build my vemto project, I get the following error below, Please how do I fix the issues ASAP

Error: Command failed: npm run build
npm ERR! Missing script: "build"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kodekribtech/.npm/_logs/2022-11-01T08_06_37_952Z-debug-0.log

    at checkExecSyncError (child_process.js:634:11)
    at execSync (child_process.js:670:15)
    at electron/js2c/asar.js:727:23
    at u.executeCommand (app://./js/chunk-common.9f1d38d9.js:1:41462)
    at u.executeNpm (app://./js/chunk-common.9f1d38d9.js:1:41152)
    at Re.compileAssets (app://./js/generator.852f910b.js:1:38941)
    at app://./js/generator.852f910b.js:1:38096
    at new Promise ()
    at Re.runCommands (app://./js/generator.852f910b.js:1:38041)
    at Re.start (app://./js/generator.852f910b.js:1:38006)

**Comment by TiagoSilvaPereira** [comment]
Hi @kodekrib, you probably changed the Assets Builder from Vite to Mix, but it is not supported for new projects. Please change the Assets Builder to Vite under the project settings

**Comment by kodekrib** [comment]
Ok let me try that. Thanks for letting me know
