### ISSUE TITLE
can't open file

### ISSUE THREAD

**Issue by fredyns** [TiagoSilvaPereira/vemto-issues#386]
```
TypeError: Cannot read property 'entity' of null
    at app://./js/project_schema.cd2cba9a.js:1:121246
    at Array.forEach (<anonymous>)
    at app://./js/project_schema.cd2cba9a.js:1:121198
    at Array.forEach (<anonymous>)
    at o.getConnections (app://./js/project_schema.cd2cba9a.js:1:120991)
    at o.<anonymous> (app://./js/project_schema.cd2cba9a.js:1:120246)
    at Array.<anonymous> (app://./js/chunk-vendors.6b4aecd2.js:620:12909)
    at dt (app://./js/chunk-vendors.6b4aecd2.js:620:12304)
```

---

vemto 1.1.9
Electron 8.5.5
win32 10.0.22000
Locale: en-US

**Comment by fredyns** [comment]
relationship lines gone
![vemto eror](https://user-images.githubusercontent.com/4033019/199426404-324ef12e-06e9-4586-bc1b-8c19fecf4f4b.png)

**Comment by TiagoSilvaPereira** [comment]
Closing due to lack of details
