### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by sloanja** [TiagoSilvaPereira/vemto-issues#392]
```
TypeError: Cannot read property 'getDefaultSettingsByName' of undefined
    at Function.fromForeign (app://./js/chunk-common.99e7aeac.js:1:67527)
    at Function.getCorrectInputFromFieldAndCrud (app://./js/chunk-common.99e7aeac.js:1:66633)
    at Proxy.addInputToCrud (app://./js/chunk-common.99e7aeac.js:1:25537)
    at app://./js/chunk-common.99e7aeac.js:1:35021
    at Array.forEach (<anonymous>)
    at Proxy.addInputsFromModel (app://./js/chunk-common.99e7aeac.js:1:35008)
    at Function.fromModel (app://./js/chunk-common.99e7aeac.js:1:34345)
    at Function.createFromCrudAndRelationship (app://./js/chunk-common.99e7aeac.js:1:1122)
    at o.create (app://./js/project_crud.a0c809af.js:1:63496)
    at app://./js/project_crud.a0c809af.js:1:63457
```

---

vemto 1.1.9
Electron 8.5.5
win32 10.0.17763
Locale: en-US

**Comment by TiagoSilvaPereira** [comment]
@sloanja thanks for reporting, I check it ASAP
