### ISSUE TITLE
code generation fails 1.2.0

### ISSUE THREAD

**Issue by t0nka** [TiagoSilvaPereira/vemto-issues#395]
Unhandled Promise Rejection
TypeError: this.crud.dependentSelects is not iterable
    at Object.eval (eval at compile (app://./js/chunk-vendors.3a07e361.js:80:8946), <anonymous>:37:33)
    at i.compile (app://./js/chunk-vendors.3a07e361.js:80:8979)
    at i.compileWithErrorTreatment (app://./js/chunk-vendors.3a07e361.js:80:8839)
    at l.compile (app://./js/chunk-common.5adef34b.js:1:97372)
    at l.compileFromFile (app://./js/chunk-common.5adef34b.js:1:97200)
    at o.renderToString (app://./js/chunk-common.5adef34b.js:1:100402)
    at o.render (app://./js/chunk-common.5adef34b.js:1:99660)
    at Ft.generateCrud (app://./js/generator.949dfff3.js:1:52764)
    at Ft.generateCruds (app://./js/generator.949dfff3.js:1:51921)
    at Ft.generate (app://./js/generator.949dfff3.js:1:51008)

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/4823546/202475520-b2445e1b-2483-469c-8926-70ea6e8defb7.png">

**Comment by t0nka** [comment]
on existing projects, running mac os

**Comment by TiagoSilvaPereira** [comment]
@t0nka sorry for that, I'm already fixing it

**Comment by TiagoSilvaPereira** [comment]
@t0nka fixed, please upgrade to 1.2.1

**Comment by t0nka** [comment]
@TiagoSilvaPereira works as aspected! :-)
