### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ghinozzi** [TiagoSilvaPereira/vemto-issues#413]
```
TypeError: Cannot read property 'entity' of null
    at app://./js/project_schema.a91e256c.js:1:119859
    at Array.forEach (<anonymous>)
    at app://./js/project_schema.a91e256c.js:1:119811
    at Array.forEach (<anonymous>)
    at o.getConnections (app://./js/project_schema.a91e256c.js:1:119604)
    at o.<anonymous> (app://./js/project_schema.a91e256c.js:1:118859)
    at Array.<anonymous> (app://./js/chunk-vendors.0f6f3157.js:620:12909)
    at dt (app://./js/chunk-vendors.0f6f3157.js:620:12304)
```

---

vemto 1.3.1
Electron 8.5.5
win32 10.0.22621
Locale: pt-BR

**Comment by TiagoSilvaPereira** [comment]
@ghinozzi could you share your project .vemto file?

**Comment by ghinozzi** [comment]
[projeto-vemto-export.zip](https://github.com/TiagoSilvaPereira/vemto-issues/files/10959845/projeto-vemto-export.zip)

**Comment by TiagoSilvaPereira** [comment]
Hi @ghinozzi I managed to recover the project, but a few relationships were probably lost. I believe the database must have crashed while writing the data. I believe it shouldn't happen again since it's the first time I've seen this problem in two and a half years of Vemto's existence.

[project.zip](https://github.com/TiagoSilvaPereira/vemto-issues/files/10960686/project.zip)
