### ISSUE TITLE
issue on generate - new project just user table

### ISSUE THREAD

**Issue by craigvc** [TiagoSilvaPereira/vemto-issues#424]
Attention: Please use the Discussions page for feature requests or suggestions instead of opening a new issue.

**Describe the bug**
new project > generate
**To Reproduce**
Command failed: npm run build
/Users/craig/PhpstormProjects/vemto/test/node_modules/vite/bin/vite.js:2
import { performance } from 'node:perf_hooks'
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:703:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
    at internal/main/run_main_module.js:17:11

**Comment by YoranBosman** [comment]
For me empty projects also fail because it depends on non existing vite plugin 0.7.5
changing to 0.7.4 works.
Then on second run npm build exists saying, laravel is not a function

**Comment by TiagoSilvaPereira** [comment]
@craigvc please try downgrading Vite to 0.7.4 for now
