### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by bo3bdo** [TiagoSilvaPereira/vemto-issues#426]
```
TypeError: Cannot read property '0' of undefined
    at t.jsPlumbInstance.pt [as updateOffset] (app://./js/project_schema.a91e256c.js:1:193037)
    at t.jsPlumbInstance.revalidate (app://./js/project_schema.a91e256c.js:1:203682)
    at app://./js/project_schema.a91e256c.js:1:119529
    at NodeList.forEach (<anonymous>)
    at o.repaint (app://./js/project_schema.a91e256c.js:1:119514)
    at o.replumb (app://./js/project_schema.a91e256c.js:1:119448)
    at app://./js/project_schema.a91e256c.js:1:116492
```

---

vemto 1.3.2
Electron 8.5.5
win32 10.0.22621
Locale: en-US

**Comment by TiagoSilvaPereira** [comment]
Hi @bo3bdo could you please share your .vemto file so I can import and check what is happening?

**Comment by bo3bdo** [comment]
> Hi @bo3bdo could you please share your .vemto file so I can import and check what is happening?

yes Tiago
[attendanceinfo.zip](https://github.com/TiagoSilvaPereira/vemto-issues/files/11460032/attendanceinfo.zip)

**Comment by TiagoSilvaPereira** [comment]
Hi @bo3bdo I tried to reproduce but the error is not happening here. When does it happen to you?

**Comment by bo3bdo** [comment]
I was working on a database Migrations with add notes to it

**Comment by TiagoSilvaPereira** [comment]
@bo3bdo could you record a small video showing the moment the problem happens? Thanks
