### ISSUE TITLE
spatie

### ISSUE THREAD

**Issue by dercdevil** [TiagoSilvaPereira/vemto-issues#436]
```
Error: Command failed: "C:\xampp\php\php" artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider"
    at checkExecSyncError (child_process.js:634:11)
    at execSync (child_process.js:670:15)
    at electron/js2c/asar.js:727:23
    at u.executeCommand (app://./js/chunk-common.918af31f.js:1:41909)
    at u.executeArtisan (app://./js/chunk-common.918af31f.js:1:40809)
    at Ft.publishMigrations (app://./js/generator.23a403f8.js:1:51271)
    at Ft.generate (app://./js/generator.23a403f8.js:1:51032)
    at Ft.start (app://./js/generator.23a403f8.js:1:50999)
    at At.callProjectGenerators (app://./js/generator.23a403f8.js:1:57711)
    at async app://./js/generator.23a403f8.js:1:56637
```

---

vemto 1.3.3
Electron 8.5.5
win32 10.0.22621
Locale: es

**Comment by TiagoSilvaPereira** [comment]
@dercdevil could you please record a video showing the whole process before the throwing the error?
