### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by vogarnk** [TiagoSilvaPereira/vemto-issues#437]
```
Error: Request failed with status code 500
    at e.exports (app://./js/chunk-vendors.0f6f3157.js:80:13835)
    at e.exports (app://./js/chunk-vendors.0f6f3157.js:266:2286)
    at XMLHttpRequest.E (app://./js/chunk-vendors.0f6f3157.js:645:2151)
```

---

vemto 1.3.3
Electron 8.5.5
win32 10.0.19044
Locale: es

**Comment by TiagoSilvaPereira** [comment]
Hi @vogarnk our API was down... we already fixed it
