### ISSUE TITLE
just popped out when trying to open a project

### ISSUE THREAD

**Issue by najixp** [TiagoSilvaPereira/vemto-issues#438]
```
Error: Request failed with status code 429
    at e.exports (app://./js/chunk-vendors.0f6f3157.js:80:13835)
    at e.exports (app://./js/chunk-vendors.0f6f3157.js:266:2286)
    at XMLHttpRequest.E (app://./js/chunk-vendors.0f6f3157.js:645:2151)
```

---

vemto 1.3.3
Electron 8.5.5
win32 10.0.19045
Locale: en-US

**Comment by TiagoSilvaPereira** [comment]
Hi @najixp is this still happening? I think this was a temporary problem

**Comment by najixp** [comment]
Thanks for reply
I think it is a temporary issue I just restarted the app and everything went fine.
Thanks
