### ISSUE TITLE
Tried to export, change Laravel version to 10, re-import, got this error.  

### ISSUE THREAD

**Issue by EllisonTravel** [TiagoSilvaPereira/vemto-issues#440]
```
NonError: ErrorEvent { isTrusted: [Getter] }
    at module.exports (C:\Users\PauloB\AppData\Local\Programs\vemto\resources\app.asar\node_modules\ensure-error\index.js:20:10)
    at f (app://./js/chunk-common.918af31f.js:1:130219)
    at app://./js/chunk-common.918af31f.js:1:130916
    at _ (app://./js/chunk-vendors.0f6f3157.js:90:49773)
    at D (app://./js/chunk-vendors.0f6f3157.js:90:50037)
    at v (app://./js/chunk-vendors.0f6f3157.js:90:49989)
```

---

vemto 1.3.3
Electron 8.5.5
win32 10.0.22621
Locale: en-US

**Comment by TiagoSilvaPereira** [comment]
@EllisonTravel I replied to you on email, thanks
