### ISSUE TITLE
Generating factories not working

### ISSUE THREAD

**Issue by ArtrenH** [TiagoSilvaPereira/vemto-issues#456]
Attention: Please use the Discussions page for feature requests or suggestions instead of opening a new issue.

**Describe the bug**
When I try to generate my Laravel project, I get a 
```
Parse Error : syntax error, unexpected 'Function' (T_FUNCTION), expecting ';' on line 5
  3 | namespace Database\Factories;
  4 |
> 5 | use App\Models\Function;
    |               ^
  6 | use Illuminate\Support\Str;
  7 | use Illuminate\Database\Eloquent\Factories\Factory;
  8 |
```
 Full stacktrace:
```
SyntaxError: Parse Error : syntax error, unexpected 'Function' (T_FUNCTION), expecting ';' on line 5
  3 | namespace Database\Factories;
  4 |
> 5 | use App\Models\Function;
    |               ^
  6 | use Illuminate\Support\Str;
  7 | use Illuminate\Database\Eloquent\Factories\Factory;
  8 |
    at A.raiseError (app://./js/chunk-vendors.3a07e361.js:750:3299230)
    at A.error (app://./js/chunk-vendors.3a07e361.js:750:3299870)
    at A.expect (app://./js/chunk-vendors.3a07e361.js:750:3301395)
    at A.read_use_statement (app://./js/chunk-vendors.3a07e361.js:750:3323933)
    at A.read_top_statement (app://./js/chunk-vendors.3a07e361.js:750:3284116)
    at A.read_top_statements (app://./js/chunk-vendors.3a07e361.js:750:3283638)
    at A.read_namespace (app://./js/chunk-vendors.3a07e361.js:750:3322607)
    at A.read_start (app://./js/chunk-vendors.3a07e361.js:750:3322312)
    at A.parse (app://./js/chunk-vendors.3a07e361.js:750:3298614)
    at Ut.parseCode (app://./js/chunk-vendors.3a07e361.js:750:3352312)
```

**To Reproduce**
Generate my (complex) code with many relationships, sorry but I can't describe it better...

**Expected behavior**
No Error

**Screenshots**
see the stacktraces above

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: probably Chrome
 - Version: 1.3.3 (Vemto Version)

**Additional Notes**

Im generating the code from scratch. The directory where I create the project is empty.

**Comment by ArtrenH** [comment]
It was a me-problem. I cant name a class "Function" in php because it is a reserved keyword.
