### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by kirchaj** [TiagoSilvaPereira/vemto-issues#50]
```
Error: Navigation cancelled from "/" to "/projects/2/schema" with a new navigation.
    at We (app://./js/chunk-vendors.6bc08ad9.js:202:17387)
    at Ue (app://./js/chunk-vendors.6bc08ad9.js:202:17121)
    at f (app://./js/chunk-vendors.6bc08ad9.js:202:21301)
    at r (app://./js/chunk-vendors.6bc08ad9.js:202:16712)
    at je (app://./js/chunk-vendors.6bc08ad9.js:202:16749)
    at app://./js/chunk-vendors.6bc08ad9.js:202:21649
    at r (app://./js/chunk-vendors.6bc08ad9.js:202:16703)
    at app://./js/chunk-vendors.6bc08ad9.js:202:16731
    at app://./js/chunk-vendors.6bc08ad9.js:202:21560
    at app://./js/chunk-vendors.6bc08ad9.js:202:18041
```

---

vemto 0.6.2
Electron 8.5.2
win32 10.0.19041
Locale: en-US

**Comment by TiagoSilvaPereira** [comment]
Hi @kirchaj thank you for reporting it... I'm closing due to duplication (#46).
