### ISSUE TITLE
[BUG] Unhandled Promise Rejection with wrong Foreign Key: "Cannot read property 'type' of null"

### ISSUE THREAD

**Issue by TiagoSilvaPereira** [TiagoSilvaPereira/vemto-issues#51]
**Describe the bug**
If the user creates a foreign key without a relationship and tries to create a relationship select, it will fail with "Unhandled Promise Rejection" with the following error:

```
TypeError: Cannot read property 'type' of null
    at a.create (app://./js/project_crud.62d63bba.js:1:26228)
    at app://./js/project_crud.62d63bba.js:1:26110
```

**Expected behavior**
Create a basic field, not a relationship field, if the FK doesn't have a relationship

**Screenshots**
![image](https://user-images.githubusercontent.com/11933789/101928485-6afc3e00-3bb4-11eb-8aae-c1f1a4a0e3e9.png)

**Comment by TiagoSilvaPereira** [comment]
Fixed on 0.6.3
