### ISSUE TITLE
Error on Generating already existing Vemto Project

### ISSUE THREAD

**Issue by niphint** [TiagoSilvaPereira/vemto-issues#58]
Hi, i just tried Generate on a directory where i have a vemto project already. That was created from another PC. I added "<$DIRECTORY> to hide my local directory.
The error comes in a standard windows error window, not in vemto.

```
Error: ENOENT: no such file or directory, open '<$DIRECTORY>.env.example'
    at Object.openSync (fs.js:440:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.readFileSync (fs.js:342:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at D.readFile (app://./js/generator.484cd500.js:1:6554)
    at Pe.start (app://./js/generator.484cd500.js:1:22921)
    at ut.callProjectGenerators (app://./js/generator.484cd500.js:1:34845)
    at app://./js/generator.484cd500.js:1:34662
```

---

vemto 0.5.10
Electron 8.5.2
win32 10.0.18363
Locale: de

**Comment by TiagoSilvaPereira** [comment]
Hi @niphint please create the file .env.example inside your project folder, as you can see here on the Laravel repository: https://github.com/laravel/laravel/blob/8.x/.env.example to solve the problem (this file is created automatically when generating a Laravel project so, I think, it was not copied to the other computer, probably because it is generally a hidden file)
