### ISSUE TITLE
[BUG] Suddenly error when adding new CRUD

### ISSUE THREAD

**Issue by halimdirgantara** [TiagoSilvaPereira/vemto-issues#74]
```
TypeError: Cannot read property 'validation' of undefined
    at Function.fromFieldTypeSettings (app://./js/chunk-common.f141e59c.js:1:42205)
    at Function.fromFieldDefaultSettings (app://./js/chunk-common.f141e59c.js:1:42115)
    at Function.fromField (app://./js/chunk-common.f141e59c.js:1:41923)
    at Proxy.addInputToCrud (app://./js/chunk-common.f141e59c.js:1:17866)
    at a.create (app://./js/project_crud.2431afb4.js:1:26216)
    at app://./js/project_crud.2431afb4.js:1:26126
```

---

vemto 0.7.3
Electron 8.5.5
win32 10.0.19042
Locale: en-US

**Comment by TiagoSilvaPereira** [comment]
Hi, @halimdirgantara thank you for reporting... could you please share a small sequence of prints showing your schema and the CRUD creation process?

**Comment by TiagoSilvaPereira** [comment]
Hi @halimdirgantara could you please share more details about your schema?

**Comment by halimdirgantara** [comment]
Done, actually i forgot to set data type in model.
case closed
